full_name = input("[input] full name: ")
age = input("[input] age: ")
gpa = input("[input] gpa: ")
married_tatus = input("[input] married status: ")
print("---")
print(f"full name: {full_name}")
print(f"age: {age}")
print(f"gpa: {gpa}")
print(f"married status: {married_tatus}")